### ISSUE TITLE
未来会支持 vmess+ws+tls 吗？

### ISSUE THREAD

**Issue by nikkau** [ylxdzsw/v2socks#1]
作者你好，感觉用 rust 写的应该性能会比较好，现在 vmess 不好用了，大部分都用 ws-tls，请问未来会支持吗？

**Comment by ylxdzsw** [comment]
vmess 我暂时用着还没问题，要是哪天用不了了大概会加上吧。。另外虽然是 Rust 写的，但是并没有做任何优化，性能其实不一定好。
