### ISSUE TITLE
cargo build --release遇错

### ISSUE THREAD

**Issue by briteming** [ylxdzsw/v2socks#2]
在mac上。
git clone https://github.com/ylxdzsw/v2socks v2socks-by-ylxdzsw
cd v2socks-by-ylxdzsw
cargo build --release
显示：
    Updating git repository `https://github.com/ylxdzsw/oh-my-rust`
warning: spurious network error (2 tries remaining): failed to connect to github.com: Operation timed out; class=Os (2)
warning: spurious network error (1 tries remaining): failed to connect to github.com: Operation timed out; class=Os (2)
^C

我挂了vpn后，还是遇到同样的错误。怎么解决？

**Comment by ylxdzsw** [comment]
看起来你连不上 Github 啊，你可以试试把 https://github.com/ylxdzsw/oh-my-rust 下载下来，然后把 toml 改成本地地址，像这样：https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#testing-a-bugfix

**Comment by briteming** [comment]
hi.
https://raw.githubusercontent.com/ylxdzsw/v2socks/master/Cargo.toml文件里，“oh-my-rust =”的值怎么改成本地地址？
“oh-my-rust =”的值怎么写？

**Comment by ylxdzsw** [comment]
{ path = "/path/to/downloaded/folder" }

**Comment by briteming** [comment]
还是搞不定。可否上传mac版的可执行文件到releases?

**Comment by ylxdzsw** [comment]
我没有Mac。。

**Comment by briteming** [comment]
hi.
我看了https://blog.biofan.org/2019/02/cargo-config/ ，于是重新来过：
git clone https://github.com/ylxdzsw/v2socks v2socks-by-ylxdzsw
cd v2socks-by-ylxdzsw
nano Cargo.toml

oh-my-rust那行改为了：
oh-my-rust = { git = "https://mirrors.ustc.edu.cn/crates.io-index/" } 

然后运行：
cargo build --release
显示：
Updating git repository `https://mirrors.ustc.edu.cn/crates.io-index/`
error: failed to get `oh-my-rust` as a dependency of package `v2socks v0.2.1 (/Users/brite/v2socks-by-ylxdzsw)`

Caused by:
  failed to load source for dependency `oh-my-rust`

Caused by:
  Unable to update https://mirrors.ustc.edu.cn/crates.io-index/

Caused by:
  Could not find Cargo.toml in `/Users/brite/.cargo/git/checkouts/crates.io-index-813219bbfbc8281f/9f8cdd2`

怎么解决？

**Comment by ylxdzsw** [comment]
这么改不太对，git = 后面应该接那个包的仓库。你用 path = 的方法报什么问题？

**Comment by briteming** [comment]
1. 用 path = 的方法报什么问题？依旧显示“warning: spurious network error ”
2. “git = 后面应该接那个包的仓库”，你是说应该写为：
oh-my-rust = { git = "git://mirrors.ustc.edu.cn/crates.io-index/" }
但是这样做后，还是遇错。
3.你没有Mac。但是不能交叉编译的吗？我看到很多程序员虽然没有mac,但是仍然交叉编译出mac版。我不太熟悉具体怎么交叉编译。

**Comment by ylxdzsw** [comment]
研究了一下 github action，现在编译出了 Mac 版本，在 https://github.com/ylxdzsw/v2socks/releases/tag/v0.2.2 就可以下 (darwin) 那个～ 不过没有测试，不知道能不能跑。
